package org.jesperancinha.shell.client.costumes;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;

import javax.xml.namespace.QName;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.220+01:00
 * Generated source version: 3.3.4
 */
@WebServiceClient(name = "SeaShellsWSDLCostumes",
        wsdlLocation = "file:SeaShellsWSDLCostumes.wsdl",
        targetNamespace = "http://org.jesperancinha.shells/SeaShellsWSDLCostumes/")
public class SeaShellsWSDLCostumesService extends Service {

    public final static QName SeaShellsWSDLCostumesSOAP = new QName("http://org.jesperancinha.shells/SeaShellsWSDLCostumes/", "SeaShellsWSDLCostumesSOAP");

    public SeaShellsWSDLCostumesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * @return returns SeaShellsWSDLCostumes
     */
    @WebEndpoint(name = "SeaShellsWSDLCostumesSOAP")
    public SeaShellsWSDLCostumes getSeaShellsWSDLCostumesSOAP() {
        return super.getPort(SeaShellsWSDLCostumesSOAP, SeaShellsWSDLCostumes.class);
    }
}
