package org.jesperancinha.shell.client.costumes;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import wiremock.org.apache.commons.logging.Log;
import wiremock.org.apache.commons.logging.LogFactory;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.141+01:00
 * Generated source version: 3.3.4
 */
public final class SeaShellsWSDLCostumesClient extends SeaShellsWSDLCostumesAbstract {

    private final static Log log = LogFactory.getLog(SeaShellsWSDLCostumesClient.class);

    private static final QName SERVICE_NAME = new QName("http://org.jesperancinha.shells/SeaShellsWSDLCostumes/", "SeaShellsWSDLCostumes");

    private final SeaShellsWSDLCostumes port;

    public SeaShellsWSDLCostumesClient(String[] args) throws MalformedURLException, URISyntaxException {
        super(args);
        this.port = getSeaShellsWSDLCostumes();
    }

    public SeaShellsWSDLCostumesClient(URL url) {
        super(url);
        this.port = getSeaShellsWSDLCostumes();
    }

    public Costume getItem(Long costumeId) {
        try {
            log.trace("Invoking costumes...");
            Costume costumesReturn = port.costumes(costumeId);
            log.trace("costumes.result=" + costumesReturn);
            return costumesReturn;
        } catch (Exception e) {
            log.error("", e);
        }
        return null;
    }

    private SeaShellsWSDLCostumes getSeaShellsWSDLCostumes() {
        SeaShellsWSDLCostumesService ss = new SeaShellsWSDLCostumesService(url, SERVICE_NAME);
        return ss.getSeaShellsWSDLCostumesSOAP();
    }

    public URL getLocalWsdlLocation() throws MalformedURLException, URISyntaxException {
        return SeaShellsWSDLCostumesClient.class.getResource("/SeaShellsWSDLCostumes.wsdl").toURI().toURL();
    }

}
