version: "3.7"
services:
  sea-shell-archiver:
    hostname: sea-shell-archiver
    build:
      context: .

  sea-shell-soap-legacy:
    hostname: sea-shell-soap-legacy
    build:
      context: sea-shell-soap-wiremock/.

