version: "3.7"
services:
  sea-shell-archiver:
    hostname: sea-shell-archiver
    build:
      context: .
    networks:
      - sea-shells-network

  sea-shell-soap-legacy:
    hostname: sea-shell-soap-legacy
    build:
      context: sea-shell-soap-wiremock/.
    networks:
      - sea-shells-network

networks:
  sea-shells-network: