package org.jesperancinha.shell.client.shells;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.URL;
import java.util.List;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.220+01:00
 * Generated source version: 3.3.4
 */
@WebServiceClient(name = "SeaShellsWSDLShells",
        wsdlLocation = "file:SeaShellsWSDLShells.wsdl",
        targetNamespace = "http://org.jesperancinha.shells/SeaShellsWSDLShells/")
public class SeaShellsWSDLShellsService extends Service {

    public final static QName SeaShellsWSDLShellsSOAP = new QName("http://org.jesperancinha.shells/SeaShellsWSDLShells/", "SeaShellsWSDLShellsSOAP");

    public SeaShellsWSDLShellsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * @return returns SeaShellsWSDLShells
     */
    @WebEndpoint(name = "SeaShellsWSDLShellsSOAP")
    public SeaShellsWSDLShells getSeaShellsWSDLShellsSOAP() {
        return super.getPort(SeaShellsWSDLShellsSOAP, SeaShellsWSDLShells.class);
    }

}
