package org.jesperancinha.shell.client.costumes;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.214+01:00
 * Generated source version: 3.3.4
 */
@WebService(targetNamespace = "http://costumeor/SeaShellsWSDLCostumes/",
        name = "SeaShellsWSDLCostumes")
@XmlSeeAlso({ObjectFactory.class})
public interface SeaShellsWSDLCostumes {

    @WebMethod(action = "http://org.jesperancinha.shells/SeaShellsWSDLCostumes/costumes")
    @RequestWrapper(localName = "costumes",
            targetNamespace = "http://org.jesperancinha.shells/SeaShellsWSDLCostumes/",
            className = "org.jesperancinha.shell.client.costumes.Costumes")
    @ResponseWrapper(localName = "costumesResponse",
            targetNamespace = "http://org.jesperancinha.shells/SeaShellsWSDLCostumes/",
            className = "org.jesperancinha.shell.client.costumes.CostumesResponse")
    @WebResult(name = "Costume",
            targetNamespace = "")
    Costume costumes(
            @WebParam(name = "costumeId",
                    targetNamespace = "")
                    long costumeId);
}
