package org.jesperancinha.shell.client.persons;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.220+01:00
 * Generated source version: 3.3.4
 */
@WebServiceClient(name = "SeaShellsWSDLPersons",
        wsdlLocation = "file:SeaShellsWSDLPersons.wsdl",
        targetNamespace = "http://org.jesperancinha.shells/SeaShellsWSDLPersons/")
public class SeaShellsWSDLPersonsService extends Service {

    public final static QName SeaShellsWSDLPersonsSOAP = new QName("http://org.jesperancinha.shells/SeaShellsWSDLPersons/", "SeaShellsWSDLPersonsSOAP");

    public SeaShellsWSDLPersonsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * @return returns SeaShellsWSDLPersons
     */
    @WebEndpoint(name = "SeaShellsWSDLPersonsSOAP")
    public SeaShellsWSDLPersons getSeaShellsWSDLPersonsSOAP() {
        return super.getPort(SeaShellsWSDLPersonsSOAP, SeaShellsWSDLPersons.class);
    }
}
