
package org.jesperancinha.shell.client.persons;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.141+01:00
 * Generated source version: 3.3.4
 *
 */
public final class SeaShellsWSDLFile_SeaShellsWSDLFileSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://org.jesperancinha.shells/SeaShellsWSDLFile/", "SeaShellsWSDLFile");

    private SeaShellsWSDLFile_SeaShellsWSDLFileSOAP_Client() {
    }

    public static void main(String[] args) throws Exception {
        URL wsdlURL = SeaShellsWSDLFile_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        SeaShellsWSDLFile_Service ss = new SeaShellsWSDLFile_Service(wsdlURL, SERVICE_NAME);
        SeaShellsWSDLFile port = ss.getSeaShellsWSDLFileSOAP();

        {
        System.out.println("Invoking persons...");
        int _persons_personId = 1;
        Person _persons__return = port.persons(_persons_personId);
        System.out.println("persons.result=" + _persons__return);


        }

        System.exit(0);
    }

}
