package org.jesperancinha.shell.client.persons;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.220+01:00
 * Generated source version: 3.3.4
 *
 */
@WebServiceClient(name = "SeaShellsWSDLFile",
                  wsdlLocation = "file:SeaShellsWSDLFile.wsdl",
                  targetNamespace = "http://org.jesperancinha.shells/SeaShellsWSDLFile/")
public class SeaShellsWSDLFile_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://org.jesperancinha.shells/SeaShellsWSDLFile/", "SeaShellsWSDLFile");
    public final static QName SeaShellsWSDLFileSOAP = new QName("http://org.jesperancinha.shells/SeaShellsWSDLFile/", "SeaShellsWSDLFileSOAP");
    static {
        URL url = null;
        try {
            url = new URL("SeaShellsWSDLFile.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SeaShellsWSDLFile_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:SeaShellsWSDLFile.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SeaShellsWSDLFile_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SeaShellsWSDLFile_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SeaShellsWSDLFile_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SeaShellsWSDLFile_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SeaShellsWSDLFile_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SeaShellsWSDLFile_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SeaShellsWSDLFile
     */
    @WebEndpoint(name = "SeaShellsWSDLFileSOAP")
    public SeaShellsWSDLFile getSeaShellsWSDLFileSOAP() {
        return super.getPort(SeaShellsWSDLFileSOAP, SeaShellsWSDLFile.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SeaShellsWSDLFile
     */
    @WebEndpoint(name = "SeaShellsWSDLFileSOAP")
    public SeaShellsWSDLFile getSeaShellsWSDLFileSOAP(WebServiceFeature... features) {
        return super.getPort(SeaShellsWSDLFileSOAP, SeaShellsWSDLFile.class, features);
    }

}
