package org.jesperancinha.shell.client.persons;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.214+01:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://accountor/SeaShellsWSDLFile/", name = "SeaShellsWSDLFile")
@XmlSeeAlso({ObjectFactory.class})
public interface SeaShellsWSDLFile {

    @WebMethod(action = "http://org.jesperancinha.shells/SeaShellsWSDLFile/persons")
    @RequestWrapper(localName = "persons", targetNamespace = "http://org.jesperancinha.shells/SeaShellsWSDLFile/", className = "org.example.seashellswsdlfile.Persons")
    @ResponseWrapper(localName = "personsResponse", targetNamespace = "http://org.jesperancinha.shells/SeaShellsWSDLFile/", className = "org.example.seashellswsdlfile.PersonsResponse")
    @WebResult(name = "Person", targetNamespace = "")
    public Person persons(

            @WebParam(name = "personId", targetNamespace = "")
                    int personId
    );
}
