package org.jesperancinha.shell.client.lowers;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.220+01:00
 * Generated source version: 3.3.4
 */
@WebServiceClient(name = "SeaShellsWSDLLowers",
        wsdlLocation = "file:SeaShellsWSDLLowers.wsdl",
        targetNamespace = "http://org.jesperancinha.shells/SeaShellsWSDLLowers/")
public class SeaShellsWSDLLowersService extends Service {

    public final static QName SeaShellsWSDLLowersSOAP = new QName("http://org.jesperancinha.shells/SeaShellsWSDLLowers/", "SeaShellsWSDLLowersSOAP");

    public SeaShellsWSDLLowersService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * @return returns SeaShellsWSDLLowers
     */
    @WebEndpoint(name = "SeaShellsWSDLLowersSOAP")
    public SeaShellsWSDLLowers getSeaShellsWSDLLowersSOAP() {
        return super.getPort(SeaShellsWSDLLowersSOAP, SeaShellsWSDLLowers.class);
    }
}
