package org.jesperancinha.shell.client.shells;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.214+01:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://accountor/SeaShellsWSDLShells/", name = "SeaShellsWSDLShells")
@XmlSeeAlso({ObjectFactory.class})
public interface SeaShellsWSDLShells {

    @WebMethod(action = "http://org.jesperancinha.shells/SeaShellsWSDLShells/shells")
    @RequestWrapper(localName = "shells", targetNamespace = "http://org.jesperancinha.shells/SeaShellsWSDLShells/", className = "org.jesperancinha.shell.client.shells.Shells")
    @ResponseWrapper(localName = "shellsResponse", targetNamespace = "http://org.jesperancinha.shells/SeaShellsWSDLShells/", className = "org.jesperancinha.shell.client.shells.ShellsResponse")
    @WebResult(name = "Shell", targetNamespace = "")
    public Shell shells(

            @WebParam(name = "shellId", targetNamespace = "")
                    int shellId
    );
}
