version: '3.7'
services:
  e2e-electron:
    image: "cypress/included:14.3.0"
    working_dir: /e2e
    command: "--browser electron --env host=sea-shell-archiver"
    volumes:
      - ./e2e:/e2e
    networks:
      - sea-shells-network

  e2e-chrome:
    image: "cypress/included:14.3.0"
    working_dir: /e2e
    command: "--browser chrome --env host=sea-shell-archiver"
    volumes:
      - ./e2e:/e2e
    networks:
      - sea-shells-network

  e2e-firefox:
    image: "cypress/included:14.3.0"
    working_dir: /e2e
    command: "--browser firefox --env host=sea-shell-archiver"
    volumes:
      - ./e2e:/e2e
    networks:
      - sea-shells-network

  e2e-edge:
    image: "cypress/included:14.3.0"
    working_dir: /e2e
    command: "--browser edge --env host=sea-shell-archiver"
    volumes:
      - ./e2e:/e2e
    networks:
      - sea-shells-network
