package org.jesperancinha.shell.client.tops;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import lombok.extern.slf4j.Slf4j;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.141+01:00
 * Generated source version: 3.3.4
 */
@Slf4j
public final class SeaShellsWSDLTopsClient extends SeaShellsWSDLTopAbstract {

    private static final QName SERVICE_NAME = new QName("http://org.jesperancinha.shells/SeaShellsWSDLTops/", "SeaShellsWSDLTops");

    public SeaShellsWSDLTopsClient(final String[] args) throws MalformedURLException, URISyntaxException {
        super(args);
    }

    public SeaShellsWSDLTopsClient(final URL url) {
        super(url);
    }

    @Override
    public Top getItem(Long itemId) {
        final SeaShellsWSDLTopsService ss = new SeaShellsWSDLTopsService(this.url, SERVICE_NAME);
        final SeaShellsWSDLTops port = ss.getSeaShellsWSDLTopsSOAP();
        log.trace("Invoking tops...");
        final Top topsReturn = port.tops(itemId);
        log.trace("tops.result=" + topsReturn);
        return topsReturn;
    }

    @Override
    public URL getLocalWsdlLocation() throws MalformedURLException, URISyntaxException {
        return SeaShellsWSDLTopsClient.class.getResource("/SeaShellsWSDLTops.wsdl").toURI().toURL();
    }
}
