package org.jesperancinha.shell.client.tops;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.141+01:00
 * Generated source version: 3.3.4
 */
public final class SeaShellsWSDLTopsClient {

    private static final QName SERVICE_NAME = new QName("http://org.jesperancinha.shells/SeaShellsWSDLTops/", "SeaShellsWSDLTops");

    private SeaShellsWSDLTopsClient() {
    }

    public static void main(String[] args) throws Exception {
        URL wsdlURL = SeaShellsWSDLTopsClient.class.getResource("/SeaShellsWSDLTops.wsdl").toURI().toURL();
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        SeaShellsWSDLTopsService ss = new SeaShellsWSDLTopsService(wsdlURL, SERVICE_NAME);
        SeaShellsWSDLTops port = ss.getSeaShellsWSDLTopsSOAP();

        {
            System.out.println("Invoking tops...");
            int _tops_topId = 1;
            Top _tops__return = port.tops(_tops_topId);
            System.out.println("tops.result=" + _tops__return);


        }

        System.exit(0);
    }

}
