package org.jesperancinha.shell.client.lowers;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import lombok.extern.slf4j.Slf4j;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.141+01:00
 * Generated source version: 3.3.4
 */
@Slf4j
public final class SeaShellsWSDLLowersClient extends SeaShellsWSDLLowersAbstract {

    private static final QName SERVICE_NAME = new QName("http://org.jesperancinha.shells/SeaShellsWSDLLowers/", "SeaShellsWSDLLowers");

    public SeaShellsWSDLLowersClient(final String[] args) throws MalformedURLException, URISyntaxException {
        super(args);
    }

    public SeaShellsWSDLLowersClient(final URL url) {
        super(url);
    }

    @Override
    public Lower getItem(final Long itemId) {
        final SeaShellsWSDLLowersService ss = new SeaShellsWSDLLowersService(this.url, SERVICE_NAME);
        final SeaShellsWSDLLowers port = ss.getSeaShellsWSDLLowersSOAP();
        log.trace("Invoking lowers...");
        final Lower lowersReturn = port.lowers(itemId);
        log.trace("lowers.result=" + lowersReturn);
        return lowersReturn;
    }

    @Override
    public URL getLocalWsdlLocation() throws MalformedURLException, URISyntaxException {
        return SeaShellsWSDLLowersClient.class.getResource("/SeaShellsWSDLLowers.wsdl").toURI().toURL();
    }
}
