package org.jesperancinha.shell.client.lowers;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.141+01:00
 * Generated source version: 3.3.4
 */
public final class SeaShellsWSDLLowersClient {

    private static final QName SERVICE_NAME = new QName("http://org.jesperancinha.shells/SeaShellsWSDLLowers/", "SeaShellsWSDLLowers");

    private SeaShellsWSDLLowersClient() {
    }

    public static void main(String[] args) throws Exception {
        URL wsdlURL = SeaShellsWSDLLowersClient.class.getResource("/SeaShellsWSDLLowers.wsdl").toURI().toURL();
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        SeaShellsWSDLLowersService ss = new SeaShellsWSDLLowersService(wsdlURL, SERVICE_NAME);
        SeaShellsWSDLLowers port = ss.getSeaShellsWSDLLowersSOAP();

        {
            System.out.println("Invoking lowers...");
            int _lowers_lowerId = 1;
            Lower _lowers__return = port.lowers(_lowers_lowerId);
            System.out.println("lowers.result=" + _lowers__return);


        }

        System.exit(0);
    }

}
