
package org.jesperancinha.shell.client.accounts;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.141+01:00
 * Generated source version: 3.3.4
 *
 */
public final class SeaShellsWSDLAccountsClient {

    private static final QName SERVICE_NAME = new QName("http://org.jesperancinha.shells/SeaShellsWSDLAccounts/", "SeaShellsWSDLAccounts");

    private SeaShellsWSDLAccountsClient() {
    }

    public static void main(String[] args) throws Exception {
        URL wsdlURL = SeaShellsWSDLAccountsClient.class.getResource("/SeaShellsWSDLAccounts.wsdl").toURI().toURL();
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        SeaShellsWSDLAccountsService ss =   new SeaShellsWSDLAccountsService(wsdlURL, SERVICE_NAME);
        SeaShellsWSDLAccounts port = ss.getSeaShellsWSDLAccountsSOAP();

        {
        System.out.println("Invoking accounts...");
        int _accounts_accountId = 1;
        Account _accounts__return = port.accounts(_accounts_accountId);
        System.out.println("accounts.result=" + _accounts__return);


        }

        System.exit(0);
    }

}
