package org.jesperancinha.shell.client.accounts;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.220+01:00
 * Generated source version: 3.3.4
 */
@WebServiceClient(name = "SeaShellsWSDLAccounts",
        wsdlLocation = "file:SeaShellsWSDLAccounts.wsdl",
        targetNamespace = "http://org.jesperancinha.shells/SeaShellsWSDLAccounts/")
public class SeaShellsWSDLAccountsService extends Service {

    public final static QName SeaShellsWSDLAccountsSOAP = new QName("http://org.jesperancinha.shells/SeaShellsWSDLAccounts/", "SeaShellsWSDLAccountsSOAP");

    public SeaShellsWSDLAccountsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * @return returns SeaShellsWSDLAccounts
     */
    @WebEndpoint(name = "SeaShellsWSDLAccountsSOAP")
    public SeaShellsWSDLAccounts getSeaShellsWSDLAccountsSOAP() {
        return super.getPort(SeaShellsWSDLAccountsSOAP, SeaShellsWSDLAccounts.class);
    }
}
