package org.jesperancinha.shell.client.persons;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.141+01:00
 * Generated source version: 3.3.4
 */
public final class SeaShellsWSDLPersonsClient {

    private static final QName SERVICE_NAME = new QName("http://org.jesperancinha.shells/SeaShellsWSDLPersons/", "SeaShellsWSDLPersons");

    private SeaShellsWSDLPersonsClient() {
    }

    public static void main(String[] args) throws Exception {
        URL wsdlURL = SeaShellsWSDLPersonsClient.class.getResource("/SeaShellsWSDLPersons.wsdl").toURI().toURL();
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        SeaShellsWSDLPersonsService ss = new SeaShellsWSDLPersonsService(wsdlURL, SERVICE_NAME);
        SeaShellsWSDLPersons port = ss.getSeaShellsWSDLPersonsSOAP();

        {
            System.out.println("Invoking persons...");
            int _persons_personId = 1;
            Person _persons__return = port.persons(_persons_personId);
            System.out.println("persons.result=" + _persons__return);


        }

        System.exit(0);
    }

}
