package org.jesperancinha.shell.client.lowers;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.214+01:00
 * Generated source version: 3.3.4
 */
@WebService(targetNamespace = "http://loweror/SeaShellsWSDLLowers/", name = "SeaShellsWSDLLowers")
@XmlSeeAlso({ObjectFactory.class})
public interface SeaShellsWSDLLowers {

    @WebMethod(action = "http://org.jesperancinha.shells/SeaShellsWSDLLowers/lowers")
    @RequestWrapper(localName = "lowers", targetNamespace = "http://org.jesperancinha.shells/SeaShellsWSDLLowers/", className = "org.jesperancinha.shell.client.lowers.Lowers")
    @ResponseWrapper(localName = "lowersResponse", targetNamespace = "http://org.jesperancinha.shells/SeaShellsWSDLLowers/", className = "org.jesperancinha.shell.client.lowers.LowersResponse")
    @WebResult(name = "Lower", targetNamespace = "")
    public Lower lowers(

            @WebParam(name = "lowerId", targetNamespace = "")
                    long lowerId
    );
}
