
package org.jesperancinha.shell.client.costumes;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.141+01:00
 * Generated source version: 3.3.4
 *
 */
public final class SeaShellsWSDLCostumesClient {

    private static final QName SERVICE_NAME = new QName("http://org.jesperancinha.shells/SeaShellsWSDLCostumes/", "SeaShellsWSDLCostumes");

    private SeaShellsWSDLCostumesClient() {
    }

    public static void main(String[] args) throws Exception {
        URL wsdlURL = SeaShellsWSDLCostumesClient.class.getResource("/SeaShellsWSDLCostumes.wsdl").toURI().toURL();
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        SeaShellsWSDLCostumesService ss =   new SeaShellsWSDLCostumesService(wsdlURL, SERVICE_NAME);
        SeaShellsWSDLCostumes port = ss.getSeaShellsWSDLCostumesSOAP();

        {
        System.out.println("Invoking costumes...");
        int _costumes_costumeId = 1;
        Costume _costumes__return = port.costumes(_costumes_costumeId);
        System.out.println("costumes.result=" + _costumes__return);


        }

        System.exit(0);
    }

}
