
package org.jesperancinha.shell.client.accounts;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import lombok.extern.slf4j.Slf4j;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.Optional;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.141+01:00
 * Generated source version: 3.3.4
 */
@Slf4j
public final class SeaShellsWSDLAccountsClient extends SeaShellsWSDLAccountsAbstract {

    private static final QName SERVICE_NAME = new QName("http://org.jesperancinha.shells/SeaShellsWSDLAccounts/", "SeaShellsWSDLAccounts");
    private final URL url;

    public SeaShellsWSDLAccountsClient(String[] args) throws MalformedURLException, URISyntaxException {

        this.url = getUrlFromCommandLine(args);
    }

    public SeaShellsWSDLAccountsClient(URL url) {
        this.url = url;
    }

    @Override
    public Account getItem(long accountId) {
        final SeaShellsWSDLAccountsService ss = new SeaShellsWSDLAccountsService(this.url, SERVICE_NAME);
        final SeaShellsWSDLAccounts port = ss.getSeaShellsWSDLAccountsSOAP();
        log.trace("Invoking accounts...");
        Account accounts = port.accounts(accountId);
        log.trace("accounts.result=" + accounts.toString());
        return accounts;
    }

    @Override
    public URL getLocalWsdlLocation() throws MalformedURLException, URISyntaxException {
        return SeaShellsWSDLAccountsClient.class.getResource("/SeaShellsWSDLAccounts.wsdl").toURI().toURL();
    }

}
