
package org.jesperancinha.shell.client.shells;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.141+01:00
 * Generated source version: 3.3.4
 *
 */
public final class SeaShellsWSDLShellsClient {

    private static final QName SERVICE_NAME = new QName("http://org.jesperancinha.shells/SeaShellsWSDLShells/", "SeaShellsWSDLShells");

    private SeaShellsWSDLShellsClient() {
    }

    public static void main(String[] args) throws Exception {
        URL wsdlURL = SeaShellsWSDLShellsClient.class.getResource("/SeaShellsWSDLShells.wsdl").toURI().toURL();
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        SeaShellsWSDLShellsService ss = new SeaShellsWSDLShellsService(wsdlURL, SERVICE_NAME);
        SeaShellsWSDLShells port = ss.getSeaShellsWSDLShellsSOAP();

        {
        System.out.println("Invoking shells...");
        int _shells_shellId = 1;
        Shell _shells__return = port.shells(_shells_shellId);
        System.out.println("shells.result=" + _shells__return);


        }

        System.exit(0);
    }

}
