package org.jesperancinha.shell.client.tops;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.214+01:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://accountor/SeaShellsWSDLTops/", name = "SeaShellsWSDLTops")
@XmlSeeAlso({ObjectFactory.class})
public interface SeaShellsWSDLTops {

    @WebMethod(action = "http://org.jesperancinha.shells/SeaShellsWSDLTops/tops")
    @RequestWrapper(localName = "tops", targetNamespace = "http://org.jesperancinha.shells/SeaShellsWSDLTops/", className = "org.jesperancinha.shell.client.tops.Tops")
    @ResponseWrapper(localName = "topsResponse", targetNamespace = "http://org.jesperancinha.shells/SeaShellsWSDLTops/", className = "org.jesperancinha.shell.client.tops.TopsResponse")
    @WebResult(name = "Top", targetNamespace = "")
    public Top tops(

            @WebParam(name = "topId", targetNamespace = "")
                    int topId
    );
}
