package org.jesperancinha.shell.client.tops;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-12-20T11:26:09.220+01:00
 * Generated source version: 3.3.4
 */
@WebServiceClient(name = "SeaShellsWSDLTops",
        wsdlLocation = "file:SeaShellsWSDLTops.wsdl",
        targetNamespace = "http://org.jesperancinha.shells/SeaShellsWSDLTops/")
public class SeaShellsWSDLTopsService extends Service {

    public final static QName SeaShellsWSDLTopsSOAP = new QName("http://org.jesperancinha.shells/SeaShellsWSDLTops/", "SeaShellsWSDLTopsSOAP");

    public SeaShellsWSDLTopsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * @return returns SeaShellsWSDLTops
     */
    @WebEndpoint(name = "SeaShellsWSDLTopsSOAP")
    public SeaShellsWSDLTops getSeaShellsWSDLTopsSOAP() {
        return super.getPort(SeaShellsWSDLTopsSOAP, SeaShellsWSDLTops.class);
    }
}
