name: S_ARCH sea-shell-archiver-pull-request

on:
  pull_request:
    branches: 
      - '**'
  push:
    branches:
      - '**'
      - '!master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'adopt'

        - name: Build and Test all Including Blocks
          run: mvn clean install

        - name: Build and Test all but only reportable tests
          run: mvn clean install -Preports jacoco:prepare-agent package jacoco:report
