name: S_ARCH sea-shell-archiver-pull-request

on:
  pull_request_target:
    branches:
      - '**'
  create:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'adopt'

        - name: Build and Test all Including Blocks
          run: mvn clean install

        - name: Build and Test all but only reportable tests
          run: mvn clean install -Preports jacoco:prepare-agent package jacoco:report
